name: validation

on:
  workflow_call:
#  workflow_dispatch:
    inputs:
      helm_repository:
        required: true
        type: string
#        default: kizuna1921/conftest

      helm_repository_ref:
        required: true
        type: string
#        default: main

      helm_path:
        required: true
        type: string
#        default: tmp

    secrets:
      HELM_PAT:
        required: true

jobs:
  validation:
    name: validation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: clone helm-chart repository
        uses: actions/checkout@v3
        with: 
          repository: ${{ inputs.helm_repository }}
          ref: ${{ inputs.helm_repository_ref }}
          path: ${{ inputs.helm_path }}
          token: ${{ secrets.HELM_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Get Python version
        run: python -V

      - name: install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
          chmod +x /usr/bin/yq
          yq -V

      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
          jq -V

      - name: change values.yaml 
        run: |
          cd sample-app
          yq -r .spec.source.helm.values application.yaml > ../${{ inputs.helm_path }}/values.yaml
          cat ../${{ inputs.helm_path }}/values.yaml

      - name: Helm template
        run: |
          cd ${{ inputs.helm_path }}
          helm template . > tmp.yaml
          cat tmp.yaml

      - name: delete tmp directory
        run: |
          rm -rf ${{ inputs.helm_path }}